# Generated by Django 4.0 on 2024-02-07 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasuda_qoshish', '0002_materialli_mahsulotlar_stol_stul'),
    ]

    operations = [
        migrations.CreateModel(
            name='maxsulot_qoshish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('olchami', models.CharField(max_length=20)),
                ('narxi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Toifalash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='AlohidaPasuda',
        ),
        migrations.DeleteModel(
            name='CofeBreak',
        ),
        migrations.DeleteModel(
            name='Golf',
        ),
        migrations.DeleteModel(
            name='Inventarlar',
        ),
        migrations.DeleteModel(
            name='KumushEskiPasuda',
        ),
        migrations.DeleteModel(
            name='LacostaPasuda',
        ),
        migrations.DeleteModel(
            name='Materialli_mahsulotlar',
        ),
        migrations.DeleteModel(
            name='MaterialMahsulotlar',
        ),
        migrations.DeleteModel(
            name='OqTillaPasuda',
        ),
        migrations.DeleteModel(
            name='Set_Pasuda',
        ),
        migrations.DeleteModel(
            name='Stol_stul',
        ),
        migrations.DeleteModel(
            name='YashilPasuda',
        ),
        migrations.AddField(
            model_name='maxsulot_qoshish',
            name='toifasi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pasuda_qoshish.toifalash'),
        ),
    ]
