# Generated by Django 4.0 on 2024-02-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasuda_qoshish', '0003_maxsulot_qoshish_toifalash_delete_alohidapasuda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maxsulot_qoshish',
            name='Rasm',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
