# Generated by Django 4.0 on 2024-02-10 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahifa', '0002_toifalash1_alter_statiska_soni_and_more'),
        ('pasuda_qoshish', '0004_maxsulot_qoshish_rasm'),
    ]

    operations = [
        migrations.AddField(
            model_name='maxsulot_qoshish',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sahifa.toifalash1'),
        ),
    ]
