# Generated by Django 4.0 on 2024-02-08 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sahifa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toifalash1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='statiska',
            name='soni',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='corusel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sahifa.toifalash1'),
        ),
        migrations.DeleteModel(
            name='Toifalash',
        ),
    ]
