# Generated by Django 4.0 on 2024-02-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlohidaPasuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('tarela_olchami', models.CharField(max_length=20)),
                ('narxi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CofeBreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sutol', models.CharField(max_length=100)),
                ('tarela_olchami', models.CharField(max_length=20)),
                ('narxi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Golf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('tarela_olchami', models.CharField(max_length=20)),
                ('narxi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventarlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('tarela_olchami', models.CharField(max_length=20)),
                ('narxi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KumushEskiPasuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('tarela_olchami', models.CharField(max_length=20)),
                ('narxi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LacostaPasuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('tarela_olchami', models.CharField(max_length=20)),
                ('narxi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MaterialMahsulotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('tarela_olchami', models.CharField(max_length=20)),
                ('narxi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OqTillaPasuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('tarela_olchami', models.CharField(max_length=20)),
                ('narxi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Set_Pasuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('tarela_olchami', models.CharField(max_length=20)),
                ('narxi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='YashilPasuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('tarela_olchami', models.CharField(max_length=20)),
                ('narxi', models.IntegerField()),
            ],
        ),
    ]
