# Generated by Django 4.0 on 2024-02-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasuda_qoshish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materialli_mahsulotlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('tarela_olchami', models.CharField(max_length=20)),
                ('narxi', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stol_stul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('stol_olchami', models.CharField(max_length=20)),
                ('narxi', models.IntegerField()),
            ],
        ),
    ]
